blank_issues_enabled: false # Mencegah orang membuat issue kosong tanpa template
contact_links:
  - name: Pertanyaan atau Diskusi
    url: https://github.com/orgs/kominfo-denpasar/discussions
    about: Gunakan GitHub Discussions untuk bertanya terkait teknis kode atau fitur, bukan Issue.